'use server';

import fs from 'node:fs';
import path from 'node:path';
import recursive from 'recursive-readdir';
import { BLUEPRINT_FOLDER, BLUEPRINT_IMPORTS_FILE, BLUEPRINT_IMPORTER_NAMES } from '../config/constants.js';
import { getBlueprintOptions, getComponentOptions, getFileOptions } from '../config/options.js';
import { coverageReport } from './coverageReport.js';
import { fsReadFirstLine } from '../utils/fsReadFirstLine.js';

import type { FunctionComponent } from 'react';
import type { ComponentMeta } from "../blueprint/types.js";
import type { Blueprint } from '../blueprint/Blueprint.js';

export type ProjectFiles = {
    blueprints: Record<string, string>;
    components: Record<string, {
        path: string;
        meta: ComponentMeta;
    }>;
};

export interface BlueprintImportsMap {
    [key: string]: {
        b: () => Promise<Blueprint> | Promise<{ default: Blueprint }> | Promise<undefined>;
        c: () => Promise<FunctionComponent> | Promise<{ default: FunctionComponent }> | Promise<undefined>;
        m: () => Promise<ComponentMeta> | Promise<undefined>;
    };
}

const commentDocs = `// This file is auto-generated by Blueprint at build time.
// Do not edit this manually.`;

const importTemplates = {
    es6: {
        prefix: `const componentMap = {
`,
        import: 'import',
        suffix: `};
export default componentMap;`,
    },
    commonjs: {
        prefix: `const componentMap = {
`,
        import: 'import',
        suffix: `};
module.exports = componentMap;`,
    },
};

async function writeImportsFile(projectFiles: ProjectFiles) {
    const { blueprints, components } = projectFiles;
    const { importsFormat } = getFileOptions();
    const template = importTemplates[importsFormat || 'es6'];
    let fileContent = `${commentDocs}\n${template.prefix}`;
    for (const componentKey in components) {
        const component = components[componentKey];
        if (component) {
            const blueprintPath = blueprints[componentKey];
            const importB = BLUEPRINT_IMPORTER_NAMES['blueprint'];
            const importC = BLUEPRINT_IMPORTER_NAMES['component'];
            const importM = BLUEPRINT_IMPORTER_NAMES['meta'];
            const b = blueprintPath ? `${importB}: () => ${template.import}('../${blueprintPath}')` : `${importB}: () => {}`;
            const c = `${importC}: () => ${template.import}('../${component?.path}')`;
            const m = `${importM}: () => { return ${JSON.stringify(component?.meta)}; }`;
            fileContent += `'${componentKey}': {
  ${c},
  ${b},
  ${m},
},\n`;
        }
    }
    fileContent += template.suffix;

    const filePath = `${BLUEPRINT_FOLDER}/${BLUEPRINT_IMPORTS_FILE}`;
    try {
        await fs.promises.writeFile(filePath, fileContent);
    } catch (error) {
        console.error(`[Blueprint] Error writing ${filePath}`, error);
    }
}

export async function generateImports() {
    const { componentsRoot = '.', ignore = [] } = getFileOptions();
    const { matchComponent = '', readComponentMeta } = getComponentOptions();
    const { matchBlueprint = '' } = getBlueprintOptions();
    const relativeRoot = path.resolve(componentsRoot).replace(`${path.resolve('.')}/`, '') + '/';

    try {
        await fs.promises.access(componentsRoot);
    } catch {
        console.error(`[Blueprint] Unable to access components root path '${componentsRoot}'\n`);
        return;
    }

    let filesList: string[];
    try {
        filesList = await recursive(componentsRoot, ignore || []);
    } catch (err) {
        console.error(`[Blueprint] Error reading files in project`, err);
        return;
    }
    if (filesList.length === 0) {
        console.warn(`[Blueprint] Warning: No files found at components root path '${componentsRoot}'. Please check your configuration.\n`);
    }
    filesList.sort();

    const projectFiles: ProjectFiles = {
        blueprints: {},
        components: {},
    };
    for (const path of filesList) {
        const matchesBlueprint = new RegExp(matchBlueprint).exec(path);
        if (matchesBlueprint) {
            const filePath = matchesBlueprint[1] || '';
            const key = filePath.replace(relativeRoot, '');
            projectFiles.blueprints[key] = matchesBlueprint[0];
        } else {
            const matchesComponent = new RegExp(matchComponent).exec(path);
            if (matchesComponent) {
                const filePath = matchesComponent[1] || '';
                const key = filePath.replace(relativeRoot, '');

                const meta: ComponentMeta = {};
                if (readComponentMeta) {
                    const firstLine = await fsReadFirstLine(path);

                    const useClient = firstLine?.match(/^\s*['"]+use client['"]+/);
                    if (useClient) {
                        meta.useClient = true;
                    }

                    const useServer = firstLine?.match(/^\s*['"]+use server['"]+/);
                    if (useServer) {
                        meta.useServer = true;
                    }
                }

                projectFiles.components[key] = {
                    path: matchesComponent[0],
                    meta,
                };
            }
        }
    };

    await writeImportsFile(projectFiles);
    await coverageReport(componentsRoot, filesList.length, projectFiles);

    return projectFiles;
}
