import fs from 'fs';
import path from 'path';
import recursive from 'recursive-readdir';
import { getOptions } from '../config/options';
import { coverageReport } from './coverageReport';
import { BLUEPRINT_FOLDER, BLUEPRINT_IMPORTS_FILE, BLUEPRINT_IMPORTER_NAMES } from '../config/constants';

import type { BlueprintOptionsWithDefaults, ComponentMeta, ProjectFiles } from '../types';
import { fsReadFirstLine } from '../utils/fsReadFirstLine';

const commentDocs = `// This file is auto-generated by Blueprint during a Next.js build.
// Do not edit this manually.`;

const importTemplates = {
    es6: {
        prefix: `import dynamic from 'next/dynamic';
const componentMap = {
`,
        import: 'import',
        suffix: `};
export default componentMap;`,
    },
    commonjs: {
        prefix: `const nextDynamic = require('next/dynamic');
const dynamic = nextDynamic.default || nextDynamic;
const componentMap = {
`,
        import: 'require',
        suffix: `};
module.exports = componentMap;`,
    },
};

function writeImportsFile(projectFiles: ProjectFiles) {
    const { blueprints, components } = projectFiles;
    const { importsFormat } = getOptions();
    const template = importTemplates[importsFormat || 'es6'];
    let fileContent = `${commentDocs}\n${template.prefix}`;
    for (const componentKey in components) {
        const component = components[componentKey];
        if (component) {
            const blueprintPath = blueprints[componentKey];
            const importB = BLUEPRINT_IMPORTER_NAMES['blueprint'];
            const importC = BLUEPRINT_IMPORTER_NAMES['component'];
            const importM = BLUEPRINT_IMPORTER_NAMES['meta'];
            const b = blueprintPath ? `${importB}: () => ${template.import}('../${blueprintPath}')` : `${importB}: () => {}`;
            // Note: We must always use 'import()` here because 'next/dynamic' is designed to work with ES Module import() syntax,
            //  which always returns a Promise, whereas CommonJS require sometimes returns a resolved module for server-side components.
            // Alternatively, if we do not use 'next/dynamic' then we get a different error loading client-side components instead
            //  https://github.com/vercel/next.js/issues/71991
            const c = `${importC}: () => dynamic(() => import('../${component?.path}'))`;
            const m = `${importM}: () => { return ${JSON.stringify(component?.meta)}; }`;
            fileContent += `'${componentKey}': {
  ${c},
  ${b},
  ${m},
},\n`;
        }
    }
    fileContent += template.suffix;

    const filePath = `${BLUEPRINT_FOLDER}/${BLUEPRINT_IMPORTS_FILE}`;
    fs.writeFile(filePath, fileContent, (error) => {
        if (error) {
            console.error(`Error writing ${filePath}`, error);
        }
    });
}

export function generateImports() {
    const { files }: BlueprintOptionsWithDefaults = getOptions();
    const { componentsRoot, ignore, matchBlueprint, matchComponent, readComponentMeta } = files;
    const relativeRoot = path.resolve(componentsRoot).replace(`${path.resolve('.')}/`, '') + '/';

    recursive(componentsRoot, ignore || [], async (err, files) => {
        if (err) {
            console.error('Error reading files in project', err);
            return;
        }
        const projectFiles: ProjectFiles = {
            blueprints: {},
            components: {},
        };
        files.sort();
        for (const path of files) {
            const matchesBlueprint = new RegExp(matchBlueprint).exec(path);
            if (matchesBlueprint) {
                const filePath = matchesBlueprint[1] || '';
                const key = filePath.replace(relativeRoot, '');
                projectFiles.blueprints[key] = matchesBlueprint[0];
            } else {
                const matchesComponent = new RegExp(matchComponent).exec(path);
                if (matchesComponent) {
                    const filePath = matchesComponent[1] || '';
                    const key = filePath.replace(relativeRoot, '');

                    const meta: ComponentMeta = {};
                    if (readComponentMeta) {
                        const firstLine = await fsReadFirstLine(path);

                        const useClient = firstLine?.match(/^\s*['"]+use client['"]+/);
                        if (useClient) {
                            meta.useClient = true;
                        }

                        const useServer = firstLine?.match(/^\s*['"]+use server['"]+/);
                        if (useServer) {
                            meta.useServer = true;
                        }
                    }

                    projectFiles.components[key] = {
                        path: matchesComponent[0],
                        meta,
                    };
                }
            }
        };
        fs.mkdirSync(BLUEPRINT_FOLDER, { recursive: true });
        writeImportsFile(projectFiles);
        coverageReport(componentsRoot, files.length, projectFiles);
    });
}
