'use server';

import fs from 'node:fs';
import JSON5 from 'json5';
import { BLUEPRINT_FOLDER, BLUEPRINT_CONFIG_FILE } from './constants.js';
import { getFileOptions, setOptions } from './options.js';
import { readUserConfigFile } from '../_blueprint_config_builder.js';

const templates = {
    es6: {
        export: 'export default ',
    },
    commonjs: {
        export: 'module.exports = ',
    },
};

export async function buildConfig() {
    fs.mkdirSync(BLUEPRINT_FOLDER, { recursive: true });

    const userConfig = await readUserConfigFile();
    setOptions(userConfig || {});
    const { importsFormat } = getFileOptions();

    /**
     * NOTE: After testing the execution times, it is basically equivalent to just always write the file, even if there are no changes.
     * The time it takes to read the file and compare it is about the same as writing the file. So we can just write the file every time for simplicity.
     * We see the same results with both large and small config files.
     * Leave this commented out in case we want to revisit this in the future, but for now it just adds unnecessary complexity without any real performance benefit.
     */
    // const currentFile = await readSavedConfigFile();
    // if (JSON.stringify(currentFile) === JSON.stringify(userConfig)) {
    //     return; // Skip writing the file because config is not changing.
    // }

    const template = templates[importsFormat || 'es6'];
    const fileContent = `// This file is auto-generated by Blueprint at build time.
// Please add your configuration to a blueprint.config.{ts|js} file in the root of your project.
${template.export}${JSON5.stringify(userConfig || {}, null, 2)};`;

    const filePath = `${BLUEPRINT_FOLDER}/${BLUEPRINT_CONFIG_FILE}`;
    try {
        await fs.promises.writeFile(filePath, fileContent);
    } catch (error) {
        console.error(`Error writing ${filePath}`, error);
    }
}
