'use server';

import fs from 'node:fs';
import JSON5 from 'json5';
import { BLUEPRINT_FOLDER, BLUEPRINT_CONFIG_FILE } from './constants.js';
import { getFileOptions, setOptions } from './options.js';
import { readUserConfigFile } from '../_blueprint_config_builder.js';

const templates = {
    es6: {
        export: 'export default ',
    },
    commonjs: {
        export: 'module.exports = ',
    },
};

export async function buildConfig() {
    fs.mkdirSync(BLUEPRINT_FOLDER, { recursive: true });
    
    const userConfig = await readUserConfigFile();
    setOptions(userConfig || {});
    const { importsFormat } = getFileOptions();

    const template = templates[importsFormat || 'es6'];
    const fileContent = `// This file is auto-generated by Blueprint at build time.
// Please add your configuration to a blueprint.config.{ts|js} file in the root of your project.
${template.export}${JSON5.stringify(userConfig || {}, null, 2)};`;

    const filePath = `${BLUEPRINT_FOLDER}/${BLUEPRINT_CONFIG_FILE}`;
    try {
        await fs.promises.writeFile(filePath, fileContent);
    } catch (error) {
        console.error(`Error writing ${filePath}`, error);
    }
}
